#include <iostream>
#include <iomanip>
#include <cmath>
using namespace std;

int main(int argc, char** argv) {
	
	//TASK 1 PROGRAM FOR MILES PER GALLON
	
	
	float no_of_gallons;
	float total_miles;
	float miles_per_gallon;
	
	cout << " Enter number of gallons of gas the car can hold? " <<endl;
	cin >> no_of_gallons;
	
	cout << " Enter the number of miles it can be driven on a full tank? " << endl;
	cin>> total_miles;
	
	
	 miles_per_gallon=  total_miles / no_of_gallons;
	 cout << " The number of miles that may be driven per gallon of gas is " <<  miles_per_gallon <<endl << endl;
	 
	 // TASK 2 PROGRAM FOR STADIUM SEATING 

        // Price of tickets
    const int A=15;
    const int  B=12;
    const int C=9;

         // Number of tickets sold
    float sold_A;
    float sold_B;
    float sold_C;

     cout << showpoint << fixed << setprecision(2);

    cout << " Enter amount of tickets sold for class A: "<< endl;
    cin >> sold_A;

     cout << " Enter amount of tickets sold for class B: "<< endl;
     cin >> sold_B;

    cout << " Enter amount of tickets sold for class C: "<< endl;
    cin >> sold_C;

     float total_1= A * sold_A;
     float total_2= B *  sold_B; 
     float total_3= C *  sold_C;
	
    cout <<"The amount of income generated by Class A : " << total_1 << endl;
    cout << "The amount of income generated by Class B : " <<total_2 << endl;
    cout << "The amount of income generated by Class C : " <<total_3 <<endl << endl;


      // TASK 3   PROGRAM FOR INGREDIENT ADJUSTER 

   const float COOKIES = 48;
   const float SUGAR = 1.5;
   const float BUTTER = 1;
   const float FLOUR = 1.75;

   float num_cookies;
   float total_butter;
   float  total_sugar;
   float  total_flour;

    // Ask user how many cookies to make
     cout << "How many cookies do you want to make? "<< endl ;
     cin >> num_cookies;

     //  ingredients needed
     total_sugar  = (SUGAR * num_cookies) / COOKIES;
     total_flour  = (FLOUR * num_cookies) / COOKIES;
     total_butter = (BUTTER * num_cookies) / COOKIES;


       // Display amount of ingredients
      cout << setprecision(2) << fixed<< showpoint;


     cout << "To make " << num_cookies << " cookies " <<endl;
     cout << "You will need  ingredients in following amount: " <<endl;
     cout  << total_butter << " cups of butter" << endl ;
     cout << total_sugar  << " cups of sugar" << endl;
      cout << total_flour  << " cups of flour" <<endl << endl << endl;

    // TASK 4 PROGRAM FOR PIZZA PI 
	
	
	int diameter;
	float size_slice= 14.125;
	float area;
	float numb_of_slices;
	const float PI = 3.14;
	
	cout << "Enter diameter of pizza in inches: " << endl;
	cin >> diameter;
	
	area= PI * (pow(diameter,2)/ 4);
	
	numb_of_slices = area/ size_slice;
	
	cout << " The number of slices of pizza will be : " <<endl << numb_of_slices;
	return 0;
}
