# Project: lab4.5b
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = lab4.5b.o
LINKOBJ  = lab4.5b.o
LIBS     = -L"C:/Users/hp/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/hp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/hp/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/hp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/hp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/hp/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/hp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/hp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/hp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = lab4.5b.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Users\hp\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

lab4.5b.o: lab4.5b.cpp
	$(CPP) -c lab4.5b.cpp -o lab4.5b.o $(CXXFLAGS)
